#%RAML 1.0 Library
#%RAML 1.0 Library
types:
  employees:
    type: object
    description: This is users object, which will contains Users details
    properties:
      empId?: integer
      empName: string
      designation: string